# Site settings
author: Rafael Batista
title: 
header-img: img/home-bg.png
email: rafaelb24@yahoo.com
copyright_name: Rafael Batista
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  AudioInjected

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
